# Generated by Django 2.1.5 on 2020-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_model', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('variant', models.CharField(max_length=50)),
                ('Ex_showroom_price', models.FloatField()),
                ('insurance_Tp', models.CharField(max_length=30)),
                ('RTO', models.FloatField()),
                ('Gl', models.FloatField()),
                ('Acc_hel', models.FloatField()),
                ('on_road', models.FloatField()),
            ],
        ),
    ]
