# Generated by Django 2.1.5 on 2020-07-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_motors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='motors',
            name='body',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
