# Generated by Django 2.1.5 on 2020-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_motors_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='body',
            field=models.TextField(default='null'),
        ),
    ]
