# Generated by Django 2.1.5 on 2020-07-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200708_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='motors',
            name='Engine_cc',
            field=models.IntegerField(null=True),
        ),
    ]
