# Generated by Django 2.1.5 on 2020-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20200708_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='Ignition',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
