# Generated by Django 2.1.5 on 2020-07-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='comments',
        ),
    ]
