# Generated by Django 2.1.5 on 2020-07-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20200710_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.CharField(max_length=200)),
                ('var2', models.CharField(max_length=200)),
                ('var3', models.CharField(max_length=200)),
                ('var4', models.CharField(max_length=200)),
                ('var5', models.CharField(max_length=200)),
                ('bike9', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variants', to='testapp.Motors')),
            ],
        ),
        migrations.AlterField(
            model_name='chasis_suspension',
            name='Front_suspension',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel_Delivery',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='Clutch',
            field=models.CharField(max_length=50),
        ),
    ]
