# Generated by Django 2.1.5 on 2020-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_20200711_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='var3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='variants',
            name='var4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='variants',
            name='var5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
