# Generated by Django 2.1.5 on 2020-07-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_auto_20200711_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='variants_data',
            name='data',
        ),
        migrations.DeleteModel(
            name='variants',
        ),
        migrations.DeleteModel(
            name='Variants_data',
        ),
    ]
