# Generated by Django 2.1.5 on 2020-07-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_auto_20200711_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.CharField(max_length=200)),
                ('var2', models.CharField(max_length=200)),
                ('var3', models.CharField(blank=True, max_length=200)),
                ('var4', models.CharField(blank=True, max_length=200)),
                ('var5', models.CharField(blank=True, max_length=200)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variants', to='testapp.Motors')),
            ],
        ),
        migrations.CreateModel(
            name='Variants_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pictures/')),
                ('body', models.TextField(blank=True, null=True)),
                ('Ex_showroom_price', models.FloatField()),
                ('Engine_cc', models.CharField(max_length=10, null=True)),
                ('Mileage', models.CharField(max_length=10, null=True)),
                ('Max_Power', models.CharField(max_length=30, null=True)),
                ('Ignition', models.CharField(max_length=80, null=True)),
                ('insurance_Tp', models.CharField(max_length=30)),
                ('RTO', models.FloatField()),
                ('Gl', models.FloatField()),
                ('Acc_hel', models.FloatField()),
                ('on_road', models.FloatField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variants_data', to='testapp.variants')),
            ],
        ),
    ]
