# Generated by Django 2.1.5 on 2020-07-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_variants_variants_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Variants', to='testapp.Motors'),
        ),
        migrations.AlterField(
            model_name='variants_data',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
