# Generated by Django 2.1.5 on 2020-07-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_auto_20200713_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants_data',
            name='data',
        ),
        migrations.DeleteModel(
            name='Variants_data',
        ),
    ]
