# Generated by Django 2.1.5 on 2020-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_auto_20200713_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_seat_cover',
            name='bike_img',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
