# Generated by Django 2.1.5 on 2020-07-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_auto_20200713_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_img', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='seat_cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bike_img', models.ImageField(upload_to='pictures/')),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='bike_seat_cover',
        ),
    ]
