# Generated by Django 2.1.5 on 2020-07-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_bike_cover_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genuine_parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bike_img', models.ImageField(upload_to='pictures/')),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bike_cover',
            name='name',
        ),
        migrations.DeleteModel(
            name='Bike_cover',
        ),
        migrations.DeleteModel(
            name='seat_cover',
        ),
    ]
