# Generated by Django 2.1.5 on 2020-07-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0030_auto_20200713_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuine_parts_related',
            name='parts_body',
            field=models.TextField(blank=True),
        ),
    ]
