# Generated by Django 2.1.5 on 2020-07-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_genuine_parts_related_parts_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='seat_cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures/')),
                ('name', models.CharField(max_length=20)),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seat_cover', to='testapp.Genuine_parts_related')),
            ],
        ),
    ]
