# Generated by Django 2.1.5 on 2020-07-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_seat_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_relate_parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pictures/')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_relate_parts', to='testapp.Genuine_parts_related')),
            ],
        ),
        migrations.RemoveField(
            model_name='seat_cover',
            name='parts',
        ),
        migrations.DeleteModel(
            name='seat_cover',
        ),
    ]
