# Generated by Django 2.1.5 on 2020-07-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_genuine_parts_relate_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuine_parts_relate_info',
            name='MRP',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
